# Generated by Django 4.2 on 2023-05-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_verdvaktin', '0001_initial'),
        ('kisildalur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.IntegerField(max_length=100)),
                ('name', models.CharField(max_length=60)),
                ('isInStock', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_verdvaktin.cpu')),
            ],
        ),
    ]
