# Generated by Django 4.2 on 2023-05-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisildalur', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
