# Generated by Django 4.2 on 2023-05-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_verdvaktin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='regex',
            field=models.CharField(default='', max_length=50),
        ),
    ]
